# Configuração do metricbeat
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# Módulos

metricbeat.modules:

# Monitoramento do sistema

  - module: system 
    metricsets: 
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
    processes: ['.*']
    processes.include_top_n:
      by_cpu: 5
      by_memory: 5  
    cpu.metrics: ["percentages", "normalized_percentages"]

 # Monitoramento para o Nginx

  - module: nginx 
    metricsets: ["stubstatus"]
    period: 10s
    hosts: ["http://192.168.4.89:80"] 

# Monitoramento do banco de dados    
  
  - module: postgresql
    metricsets: ["database", "statement"] 
    period: 10s
    hosts: ["192.168.4.89:5432"] 
    username: "daniel"
    password: "123456"

# Monitoramento dos containers

  - module: docker 
    metricsets:
      - container
      - cpu
      - diskio
      - healthcheck
      - info
      - memory
      - network
    hosts: ["unix:///var/run/docker.sock"]  
    period: 10s  

# Configuração de saída para envio das métricas
output.elasticsearch:
  hosts: ["http://192.168.4.89:9200"]

# Configuração kibana
setup.kibana:
  host: "http://kibana:5601"

# Nao sei o que é
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  

# Logging
## Esta linha precisa ser alterada para não acumular o syslog das VMs de informações

logging.level: error


